version: 2

defaults: &defaults
  docker:
    - image: palantirtechnologies/circle-spark
  resource_class: xlarge
  environment:
    TERM: dumb


test-defaults: &test-defaults
  <<: *defaults
  environment:
    CIRCLE_TEST_REPORTS: /tmp/circle-test-reports


all-branches-and-tags: &all-branches-and-tags
  filters:
    # run on all branches and tags
    tags:
      only: /.*/


jobs:
  build-maven:
    <<: *defaults
    steps:
      # Saves us from recompiling every time...
      - restore_cache:
          keys:
            - build-maven-{{ .Branch }}-{{ .BuildNum }}
            - build-maven-{{ .Branch }}-
            - build-maven-master-
      - checkout
      - restore_cache:
          keys:
            - maven-dependency-cache-{{ checksum "pom.xml" }}
            # Fallback - see https://circleci.com/docs/2.0/configuration-reference/#example-2
            - maven-dependency-cache-
      # Given the build-maven cache, this is superfluous, but leave it in in case we will want to remove the former
      - restore_cache:
          keys:
            - build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
            - build-binaries-
      - run: |
          set -o pipefail \
          && ./build/mvn -T1C -DskipTests -Phadoop-cloud -Phadoop-palantir -Pkinesis-asl -Pkubernetes -Pyarn -Phive -Psparkr install \
            | tee -a "/tmp/mvn-install.log"
      - store_artifacts:
          path: /tmp/mvn-install.log
          destination: mvn-install.log
      # Get sbt to run trivially, ensures its launcher is downloaded under build/
      - run: ./build/sbt -h || true
      - save_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
          paths:
            - "build"
      - save_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - "~/.m2"

      # SBT dependencies

      - restore_cache:
          keys:
            - ivy-dependency-cache-{{ checksum "pom.xml" }}
            - ivy-dependency-cache-
      - run: |
          # Make sbt fetch all the external deps to ~/.ivy2 so it gets cached
          set -o pipefail \
            && ./build/sbt -Phadoop-cloud -Phadoop-palantir -Pkinesis-asl -Pkubernetes -Pyarn -Phive -Psparkr externalDependencyClasspath \
              | tee -a "/tmp/sbt-classpath.log"
      - store_artifacts:
          path: /tmp/sbt-classpath.log
          destination: sbt-classpath.log
      - save_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
          paths:
            - "~/.ivy2"
      # And finally save the whole project directory
      - save_cache:
          key: build-maven-{{ .Branch }}-{{ .BuildNum }}
          paths: .

  style-tests:
    # depends only on build-maven
    <<: *test-defaults
    steps:
      - checkout
      - restore_cache:
          key: build-maven-{{ .Branch }}-{{ .BuildNum }}
      # Need maven dependency cache, otherwise checkstyle tests fail as such:
      # Failed to execute goal on project spark-assembly_2.11: Could not resolve dependencies for project org.apache.spark:spark-assembly_2.11:pom:2.4.0-SNAPSHOT
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: |
          set -o pipefail && dev/run-style-tests.py | tee /tmp/run-style-tests.log
      - store_artifacts:
          path: /tmp/run-style-tests.log
          destination: run-style-tests.log

  build-tests:
    # depends only on build-maven
    <<: *test-defaults
    steps:
      - checkout
      - restore_cache:
          key: build-maven-{{ .Branch }}-{{ .BuildNum }}
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: |
          dev/run-build-tests.py | tee /tmp/run-build-tests.log
      - store_artifacts:
          path: /tmp/run-build-tests.log
          destination: run-build-tests.log

  build-sbt:
    <<: *defaults
    steps:
      # Saves us from recompiling every time...
      - restore_cache:
          keys:
            - build-sbt-{{ .Branch }}-{{ .BuildNum }}
            - build-sbt-{{ .Branch }}-
            - build-sbt-master-
      - checkout
      - restore_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      # Given the build-sbt cache, this is superfluous, but leave it in in case we will want to remove the former
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: |
          dev/build-apache-spark.py | tee /tmp/build-apache-spark.log
      - store_artifacts:
          path: /tmp/build-apache-spark.log
          destination: build-apache-spark.log
      # And finally save the whole project directory
      - save_cache:
          key: build-sbt-{{ .Branch }}-{{ .BuildNum }}
          paths: .
      # Also save all the target files to the workspace, as we will need them in the future
      - persist_to_workspace:
          root: .
          paths:
            - "*/target/*"

  backcompat-tests:
    # depends on build-sbt
    <<: *defaults
    steps:
      - restore_cache:
          key: build-maven-{{ .Branch }}-{{ .BuildNum }}
      - restore_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
      # TODO(dsanduleac): do we need the maven cache?
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: |
          dev/run-backcompat-tests.py | tee /tmp/run-backcompat-tests.log
      - store_artifacts:
          path: /tmp/run-backcompat-tests.log
          destination: run-backcompat-tests.log


  python-tests:
    # depends on build-sbt, so we're restoring the build-sbt cache
    <<: *defaults
    steps:
      - restore_cache:
          key: build-sbt-{{ .Branch }}-{{ .BuildNum }}
      - restore_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
      # TODO(dsanduleac): do we need the maven cache?
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: dev/run-python-tests.py


  r-tests:
    # depends on build-sbt, so we're restoring the build-sbt cache
    <<: *defaults
    steps:
      - restore_cache:
          key: build-sbt-{{ .Branch }}-{{ .BuildNum }}
      - restore_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
      # TODO(dsanduleac): do we need the maven cache?
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: dev/run-r-tests.py


  scala-tests:
    <<: *test-defaults
    # project/CirclePlugin.scala does its own test splitting in SBT based on CIRCLE_NODE_INDEX, CIRCLE_NODE_TOTAL
    parallelism: 6
    # Spark runs a lot of tests in parallel, we need 16 GB of RAM for this
    resource_class: xlarge
    steps:
      - run:
          name: Before running tests, ensure we created the CIRCLE_TEST_REPORTS directory
          command: mkdir -p $CIRCLE_TEST_REPORTS
      - restore_cache:
          key: build-sbt-{{ .Branch }}-{{ .BuildNum }}
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: ivy-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run:
          name: Run all tests
          command: set -o pipefail && HADOOP_PROFILE=hadooppalantir ./dev/run-tests | tee -a "/tmp/run-tests.log"
      - store_artifacts:
          path: /tmp/run-tests.log
          destination: run-tests.log
      - run:
          name: Collect unit tests
          command: mkdir -p /tmp/unit-tests && find . -name unit-tests.log -exec rsync -R {} /tmp/unit-tests/ \;
          when: always
      - store_artifacts:
          path: /tmp/unit-tests
      - store_test_results:
          # TODO(dsanduleac): can we use $CIRCLE_TEST_RESULTS here?
          path: /tmp/circle-test-reports
      - run:
          name: Collect yarn integration test logs
          command: |
            shopt -s nullglob
            files=(resource-managers/yarn/target/./org.apache.spark.deploy.yarn.*/*-logDir-*)
            mkdir -p /tmp/yarn-tests
            if [[ ${#files[@]} != 0 ]]; then
              rsync -Rrm "${files[@]}" /tmp/yarn-tests/
            fi
          when: always
      - store_artifacts:
          path: /tmp/yarn-tests

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: maven-dependency-cache-{{ checksum "pom.xml" }}
      - restore_cache:
          key: build-binaries-{{ checksum "build/mvn" }}-{{ checksum "build/sbt" }}
      - run: echo "user=$BINTRAY_USERNAME" > .credentials
      - run: echo "password=$BINTRAY_PASSWORD" >> .credentials
      - run: echo "realm=Bintray API Realm" >> .credentials
      - run: echo "host=api.bintray.com" >> .credentials
      - deploy: dev/publish.sh
      - store_artifacts:
          path: /tmp/make-distribution.log
          destination: make-distribution.log
      - store_artifacts:
          path: /tmp/publish_artifacts.log
          destination: publish_artifacts.log
      - deploy: curl -u $BINTRAY_USERNAME:$BINTRAY_PASSWORD -X POST https://api.bintray.com/content/palantir/releases/spark/$(git describe --tags)/publish

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-maven:
          <<: *all-branches-and-tags
      - style-tests:
          requires:
            - build-maven
          <<: *all-branches-and-tags
      - build-tests:
          requires:
            - build-maven
          <<: *all-branches-and-tags
      - build-sbt:
          requires:
            - build-maven
          <<: *all-branches-and-tags
      - backcompat-tests:
          requires:
            - build-sbt
          <<: *all-branches-and-tags
      - scala-tests:
          requires:
            - build-sbt
          <<: *all-branches-and-tags
      - python-tests:
          requires:
            - build-sbt
          <<: *all-branches-and-tags
      - r-tests:
          requires:
            - build-sbt
          <<: *all-branches-and-tags
      - deploy:
          requires:
            - build-maven
            - build-sbt
            # Tests
            - build-tests
            - backcompat-tests
            - scala-tests
            - python-tests
            - r-tests
          filters:
            tags:
              only: /[0-9]+(?:\.[0-9]+){2,}-palantir\.[0-9]+(?:\.[0-9]+)*/
            branches:
              only: master
